<!DOCTYPE html>
<html lang="en">
      <head>
        <meta charset="utf-8">
        <title>Save Our Oceans</title>

        <!-- <link rel="stylesheet" type="text/css" href="css/override.css"> -->
        
        <!--Add fonts here! -->

        <link rel="stylesheet" type="text/css" href="css/w3.css">
        <link href="https://fonts.googleapis.com/css?family=Dancing+Script|Lobster|Oswald" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="css/override.css">
        
      </head>
      <body>
        <header>
            <h1><a href="index.php">Save Our Oceans</a></h1>
        </header>
        
      <!-- Navigation bar -->
        <?php include "nav.inc";?>
      </body>
      </html>
