<!DOCTYPE html>
<html lang="en">
      <head>
        <meta charset="utf-8">
        <title>Save Our Oceans</title>

        <link rel="stylesheet" type="text/css" href="css/styles.css">
        
        <link href="https://fonts.googleapis.com/css?family=Russo+One" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Changa" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Bubblegum+Sans" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=EB+Garamond" rel="stylesheet">
      </head>
      <body>
        <div class = "headerContainer">
        <header>
            <h1><a href="index.php">Save Our Oceans</a></h1>
        </header>
        </div>
        
      <!-- Navigation bar -->
        <?php include "nav.inc";?>
      </body>
      </html>
