<!DOCTYPE html>
<html lang="en">
      <head>
        <meta charset="utf-8">
        <title>Save Our Oceans</title>

        <!-- <link rel="stylesheet" type="text/css" href="css/override.css"> -->
        
        <!--Add fonts here! -->

        <link rel="stylesheet" type="text/css" href="css/w3.css">
        <!-- <link href="https://fonts.googleapis.com/css?family=Dancing+Script|Lobster|Oswald" rel="stylesheet"> -->
        <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
        <link rel="stylesheet" type="text/css" href="css/override.css">
        
      </head>
      <body>
        
      <!-- Navigation bar -->
        <?php include "nav.inc";?>
      </body>
      </html>
