<nav class = "navbar">
	<div class="w3-bar w3-black">
		<h1 class="w3-bar-item">Save Our Oceans</h1>

  		<a href="index.php" class="w3-bar-item w3-button w3-right">Home</a>
  		<a href="pollution.php" class="w3-bar-item w3-button w3-right">Pollution</a>
  		<a href="impact.php" class="w3-bar-item w3-button w3-right">Global Impact</a>
  		<a href="survey.php" class="w3-bar-item w3-button w3-right">Survey Form</a>
	</div>
</nav>